// 내 지원서·내 경험 화면 문구. 사용자 검수 전 임시안 — 여기만 고치면 화면 전체가 바뀐다.
export const WORKSPACE_COPY = {
  tabs: { applications: "내 지원서", experiences: "내 경험", company: "내 기업" },
  status: { draft: "작성 중", analyzing: "분석 중", done: "분석 완료" },
  filters: { all: "전체", draft: "작성 중", done: "분석 완료" },
  table: { application: "회사 · 직무", deadline: "마감", status: "상태", summary: "최근 분석 요약", company: "회사", analyzedAt: "분석한 날" },
  noSummary: "아직 분석 전이에요",
  analyzingSummary: "분석하고 있어요",
  passedDeadline: "마감 지남",
  open: (name: string) => `${name} 열기`,
  companyTab: {
    start: "기업 분석하기",
    emptyTitle: "아직 기업 분석이 없어요",
    emptyDescription: "지원할 회사를 분석해 두면 여기에서 다시 볼 수 있어요.",
    failed: "분석하지 못했어요. 다시 시도해 주세요.",
  },
  newApplication: "새 지원서",
  newApplicationForm: {
    company: "회사",
    job: "직무",
    deadline: "마감일",
    submit: "만들고 쓰기 시작",
    cancel: "취소",
    pageTitle: "새 지원서",
    pageSubtitle: "채용공고를 붙이면 회사·직무를 채워 드려요. 만든 뒤 바로 작성 화면으로 넘어가요.",
    back: "마이페이지",
    basicsTitle: "지원 정보",
    companyPlaceholder: "예: CJ제일제당",
    jobPlaceholder: "예: 마케팅",
    questionsTitle: "자소서 문항",
    questionsHint: "지금 몰라도 괜찮아요. 작성 화면에서 더하거나 고칠 수 있어요.",
    companyRequired: "회사 이름을 적어 주세요.",
    limitReached: "지원서는 200개까지 만들 수 있어요.",
    createFailed: "지원서를 만들지 못했어요. 잠시 후 다시 시도해 주세요.",
  },
  deadlineNone: "마감 미정",
  deadlineToday: "오늘 마감",
  deadlinePassed: "마감",
  deadlineDays: (days: number) => `D-${days}`,
  questionLabel: (n: number) => `문항 ${n}`,
  loadError: "지원서를 불러오지 못했어요. 새로고침해 주세요.",
  diagnoseFailed: "분석 실패",
  progress: (answered: number, total: number) => `${total}문항 중 ${answered}문항 작성`,
  draftCard: {
    summary: "아직 진단받지 않은 지원서예요.",
    open: "이어서 쓰기",
  },
  editor: {
    addQuestion: "문항 추가",
    questionsLabel: "문항",
    promptLabel: "문항 원문",
    answerLabel: "답변",
    noLimit: "없음",
    removeQuestion: "문항 삭제",
    promptPlaceholder: "문항 원문을 붙여 넣으세요",
    answerPlaceholder: "답변을 직접 써 보세요. 쓰는 동안 자동으로 저장돼요.",
    charLimitLabel: "글자 수 제한",
    charCount: (withSpaces: number, withoutSpaces: number) => `공백 포함 ${withSpaces}자 · 제외 ${withoutSpaces}자`,
    overLimit: "글자 수 제한을 넘었어요",
  },
  save: {
    pending: "저장 대기 중",
    saving: "저장 중",
    saved: "저장됨",
    error: "저장하지 못했어요. 잠시 후 다시 시도해요.",
    conflict: "다른 창에서 먼저 저장했어요. 이 창의 내용은 이 기기에 보관했어요. 새로고침하면 불러올 수 있어요.",
    retry: "다시 저장",
  },
  backup: {
    notice: "저장되지 않은 내용이 이 기기에 남아 있어요.",
    restore: "이 기기에 남은 내용 불러오기",
    dismiss: "보관본 지우기",
  },
  meta: {
    edit: "수정",
    save: "저장",
    cancel: "취소",
    failed: "저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
  },
  seeded: "지난 진단의 문항을 불러왔어요. 고치면 이 지원서에 저장돼요.",
  diagnose: "자소서 분석하기",
  history: "지난 진단",
  viewReport: "리포트 보기",
  historyEmpty: "아직 진단받은 적이 없어요.",
  historyError: "지난 진단을 불러오지 못했어요. 새로고침해 주세요.",
  credits: {
    account: "내 계정",
    heading: "남은 이용권",
    essay: "자소서 진단",
    company: "기업 분석",
    count: (n: number) => `${n}회`,
    freeLeft: "무료 진단 1회가 남아 있어요",
    freeShort: "무료 1회 포함",
    buy: "이용권 사기",
    detail: "자세히 보기",
    error: "이용권 정보를 불러오지 못했어요.",
    // 폰에서는 칸 두 개 대신 한 줄로 줄인다. 기업 분석이 꺼져 있으면 그 부분은 뺀다.
    buyShort: "이용권 보기",
    compactLine: (essay: number, company: number | null) =>
      company === null ? `자소서 진단 ${essay}회` : `자소서 진단 ${essay}회 · 기업 분석 ${company}회`,
  },
  page: {
    title: "마이페이지",
    subtitle: "지원서를 쓰고, 분석받고, 내 경험을 모아 두는 곳이에요.",
  },
  draft: {
    button: "내 경험으로 초안 쓰기",
    freeNote: "하루 2개 무료",
    generating: "경험을 고르고 초안을 쓰고 있어요… (10초 정도)",
    chosenLabel: "고른 경험",
    sourceLabel: (title: string) => `출처: ${title}`,
    unsourced: "경험에서 근거를 찾지 못한 문장이에요. 사실인지 확인해 주세요.",
    blankHint: "노란 칸은 경험에 없던 내용이에요. 실제 내용으로 채워 주세요.",
    apply: "이 초안으로 채우기",
    confirmReplace: "지금 쓴 글을 이 초안으로 바꿀까요?",
    retry: "다른 경험으로 다시",
    close: "닫기",
    remaining: (n: number) => `오늘 남은 무료 초안 ${n}개`,
    noExperiences: "초안을 쓰려면 경험이 하나 이상 있어야 해요.",
    goExperiences: "내 경험 적으러 가기",
    needsMore: (text: string) => `이 문항에 쓸 경험이 부족해요. ${text}`,
    rateLimited: "오늘 무료 초안 2개를 다 썼어요. 내일 오전 9시에 다시 생겨요.",
    failed: "초안을 만들지 못했어요. 횟수는 차감되지 않았어요. 잠시 후 다시 시도해 주세요.",
    authRequired: "로그인이 풀렸어요. 다시 로그인해 주세요.",
    needPrompt: "문항 원문을 먼저 적어 주세요.",
    usedLabel: "초안에 쓴 경험",
    attachPosting: "공고 붙여넣기 (선택)",
    postingAttached: (title: string) => `붙인 공고: ${title || "제목 없음"}`,
  },
  experiences: {
    add: "직접 추가",
    addManually: "직접 추가",
    search: "경험 이름이나 내용으로 찾기",
    keywordLabel: "키워드",
    allKeywords: "전체",
    moreKeywords: (n: number) => `+${n} 더 보기`,
    lessKeywords: "접기",
    count: (n: number) => `경험 ${n}개`,
    listLabel: "경험 목록",
    noMatch: "찾는 경험이 없어요.",
    back: "목록으로",
    optional: "(선택)",
    sections: { situation: "상황", action: "내가 한 일", result: "결과" },
    free: {
      label: "어떤 경험이었나요",
      placeholder: "어떤 상황이었는지, 무엇을 했는지, 무엇이 남았는지 편하게 적어 주세요. 정해진 칸은 없어요.",
      toFields: "칸 나눠 쓰기",
      toFree: "한 칸에 자유롭게 쓰기",
      fieldsHint: "필요한 칸만 채우면 돼요.",
    },
    periodPicker: {
      start: "시작",
      end: "끝",
      ongoing: "진행 중",
      pickerLabel: (field: string) => `${field} 연·월 고르기`,
      chooseYear: "연도를 고르세요",
      chooseMonth: "월을 고르세요",
      yearLabel: (year: number) => `${year}년`,
      invalid: "2024.03 처럼 연도 4자리와 월을 적어 주세요.",
      reversed: "끝이 시작보다 빨라요. 다시 골라 주세요.",
      needStart: "시작 연·월을 먼저 적어 주세요.",
      legacy: (text: string) => `지금 적힌 기간: ${text} · 새로 고르면 바뀌어요.`,
    },
    newTitle: "새 경험",
    editTitle: "경험 수정",
    tagPlaceholder: "입력 후 Enter",
    tagRemove: (tag: string) => `${tag} 키워드 빼기`,
    empty: "아직 적어 둔 경험이 없어요. 한 번 적어 두면 다음 지원서에서 다시 꺼내 쓸 수 있어요.",
    fields: {
      title: "경험 이름",
      titlePlaceholder: "예: 손님 불만을 단골로 바꾼 3개월",
      period: "기간",
      situation: "어떤 상황이었나요",
      action: "나는 무엇을 판단하고 했나요",
      result: "그래서 무엇이 달라졌나요",
      tags: "키워드 (최대 5개)",
    },
    save: "저장",
    cancel: "취소",
    remove: "삭제",
    edit: "수정",
    more: (title: string) => `${title} 더보기`,
    titleRequired: "경험 이름을 적어 주세요.",
    limitReached: "경험은 100개까지 적어 둘 수 있어요.",
    saveFailed: "저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
    loadError: "경험을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    deleteFailed: "삭제하지 못했어요. 잠시 후 다시 시도해 주세요.",
    confirmRemove: (title: string) => `'${title}' 경험을 삭제할까요?`,
    import: {
      open: "이력서·자소서로 자동 추가",
      title: "이력서·자소서로 자동 추가",
      intro: "이력서, 예전 자소서, 포트폴리오, 활동 정리 메모 뭐든 괜찮아요. 적힌 내용만 옮기고, 없는 내용은 빈칸으로 둬요.",
      placeholder: "이력서나 자소서 내용을 여기에 붙여 넣어 주세요. 여러 개를 한꺼번에 넣어도 괜찮아요.",
      inputLabel: "이력서·자소서 붙여넣기",
      example: {
        label: "예시",
        input: "이런 글을 넣으면",
        output: "이런 경험 카드가 생겨요",
        source: [
          "카페 아르바이트 (2023.03~2023.12)",
          "· 주말마다 대기 줄이 길어 그냥 돌아가는 손님이 많았음",
          "· 주문을 미리 받는 메모판을 만들어 계산대 앞에 둠",
          "· 기다리는 시간이 줄었다는 손님 말을 자주 들음",
        ],
        title: "주말 대기 줄을 줄인 카페 아르바이트",
        period: "2023.03~2023.12",
        rows: [
          ["상황", "주말마다 대기 줄이 길어 그냥 돌아가는 손님이 많았음"],
          ["내가 한 일", "주문을 미리 받는 메모판을 만들어 계산대 앞에 둠"],
          ["결과", "기다리는 시간이 줄었다는 손님 말을 자주 들음"],
        ],
      },
      upload: "PDF·Word 파일 올리기",
      reading: "파일 읽는 중...",
      fileFailed: "파일을 읽지 못했어요. 내용을 복사해서 붙여 넣어 주세요.",
      chars: (n: number) => `${n.toLocaleString()} / 20,000자`,
      tooShort: "200자 이상 넣어 주세요.",
      quota: "하루 3번까지 무료예요.",
      remaining: (n: number) => `오늘 ${n}번 남았어요.`,
      extract: "경험 뽑기",
      extracting: "글에서 경험을 찾고 있어요",
      found: (n: number) => `경험 ${n}개를 찾았어요. 저장할 것만 골라 주세요.`,
      blank: "직접 채워 주세요",
      quoteLabel: "원문",
      similar: "비슷한 경험이 이미 있어요",
      pick: (title: string) => `'${title}' 저장하기`,
      save: (n: number) => `선택한 ${n}개 저장`,
      back: "다시 넣기",
      close: "닫기",
      rateLimited: "오늘 가져오기를 다 썼어요. 내일 오전 9시에 다시 쓸 수 있어요.",
      empty: "이 글에서는 경험을 찾지 못했어요. 직접 겪은 일이 적힌 부분을 넣어 주세요. 이번 횟수는 차감되지 않았어요.",
      failed: "잠시 문제가 생겼어요. 이번 횟수는 차감되지 않았어요.",
      network: "연결이 불안정해요. 잠시 후 다시 시도해 주세요.",
      full: (n: number) =>
        n > 0 ? `경험은 100개까지 담을 수 있어요. 지금 ${n}개 더 담을 수 있어요.` : "경험은 100개까지 담을 수 있어요. 지금은 더 담을 수 없어요.",
      titleRequired: "고른 경험에 이름을 적어 주세요.",
      saveFailed: "저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
    },
  },
} as const;
