// 내 지원서·내 경험 화면 문구. 사용자 검수 전 임시안 — 여기만 고치면 화면 전체가 바뀐다.
export const WORKSPACE_COPY = {
  tabs: { applications: "내 지원서", experiences: "내 경험" },
  newApplication: "새 지원서",
  newApplicationForm: {
    company: "회사",
    job: "직무",
    deadline: "마감일",
    submit: "만들기",
    cancel: "취소",
    companyRequired: "회사 이름을 적어 주세요.",
    limitReached: "지원서는 200개까지 만들 수 있어요.",
    createFailed: "지원서를 만들지 못했어요. 잠시 후 다시 시도해 주세요.",
  },
  deadlineNone: "마감 미정",
  deadlineToday: "오늘 마감",
  deadlinePassed: "마감",
  deadlineDays: (days: number) => `D-${days}`,
  questionLabel: (n: number) => `문항 ${n}`,
  loadError: "지원서를 불러오지 못했어요. 새로고침해 주세요.",
  diagnoseFailed: "분석 실패",
  progress: (answered: number, total: number) => `${total}문항 중 ${answered}문항 작성`,
  draftCard: {
    summary: "아직 진단받지 않은 지원서예요.",
    open: "이어서 쓰기",
  },
  editor: {
    addQuestion: "문항 추가",
    removeQuestion: "문항 삭제",
    promptPlaceholder: "문항 원문을 붙여 넣으세요",
    answerPlaceholder: "답변을 직접 써 보세요. 쓰는 동안 자동으로 저장돼요.",
    charLimitLabel: "글자 수 제한",
    charCount: (withSpaces: number, withoutSpaces: number) => `공백 포함 ${withSpaces}자 · 제외 ${withoutSpaces}자`,
    overLimit: "글자 수 제한을 넘었어요",
  },
  save: {
    pending: "저장 대기 중",
    saving: "저장 중",
    saved: "저장됨",
    error: "저장하지 못했어요. 잠시 후 다시 시도해요.",
    conflict: "다른 창에서 먼저 저장했어요. 이 창의 내용은 이 기기에 보관했어요. 새로고침하면 불러올 수 있어요.",
    retry: "다시 저장",
  },
  backup: {
    notice: "저장되지 않은 내용이 이 기기에 남아 있어요.",
    restore: "이 기기에 남은 내용 불러오기",
    dismiss: "보관본 지우기",
  },
  meta: {
    edit: "수정",
    save: "저장",
    cancel: "취소",
    failed: "저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
  },
  seeded: "지난 진단의 문항을 불러왔어요. 고치면 이 지원서에 저장돼요.",
  diagnose: "이 지원서로 진단받기",
  history: "지난 진단",
  historyEmpty: "아직 진단받은 적이 없어요.",
  historyError: "지난 진단을 불러오지 못했어요. 새로고침해 주세요.",
  credits: {
    account: "내 계정",
    heading: "남은 이용권",
    essay: "자소서 진단",
    company: "기업 분석",
    count: (n: number) => `${n}회`,
    freeLeft: "무료 진단 1회가 남아 있어요",
    buy: "이용권 사기",
    detail: "자세히 보기",
    error: "이용권 정보를 불러오지 못했어요.",
    // 폰에서는 칸 두 개 대신 한 줄로 줄인다. 기업 분석이 꺼져 있으면 그 부분은 뺀다.
    compactLine: (essay: number, company: number | null) =>
      company === null ? `자소서 진단 ${essay}회` : `자소서 진단 ${essay}회 · 기업 분석 ${company}회`,
  },
  page: {
    title: "마이페이지",
    subtitle: "지원서를 쓰고, 진단받고, 내 경험을 모아 두는 곳이에요.",
  },
  experiences: {
    add: "경험 추가",
    empty: "아직 적어 둔 경험이 없어요. 한 번 적어 두면 다음 지원서에서 다시 꺼내 쓸 수 있어요.",
    fields: {
      title: "이 경험을 한 줄로 부르면",
      titlePlaceholder: "예: 손님 불만을 단골로 바꾼 3개월",
      period: "기간",
      situation: "어떤 상황이었나요",
      action: "나는 무엇을 판단하고 했나요",
      result: "그래서 무엇이 달라졌나요",
      tags: "키워드 (쉼표로 구분, 최대 5개)",
    },
    save: "저장",
    cancel: "취소",
    remove: "삭제",
    edit: "수정",
    titleRequired: "이 경험을 한 줄로 부르는 이름을 적어 주세요.",
    limitReached: "경험은 100개까지 적어 둘 수 있어요.",
    saveFailed: "저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
    loadError: "경험을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    deleteFailed: "지우지 못했어요. 잠시 후 다시 시도해 주세요.",
    confirmRemove: (title: string) => `'${title}' 경험을 지울까요?`,
  },
} as const;
